---
# file: test.yml
- name: Test that coordinator port is allocated
  wait_for: host={{ ansible_ec2_local_ipv4|default(ansible_default_ipv4.address) }} port=8081
            connect_timeout=10 state=started
  when: coordinator is defined and coordinator
  # when: druid_role == "coordinator" 

- name: Test that overlord port is allocated
  wait_for: host={{ ansible_ec2_local_ipv4|default(ansible_default_ipv4.address) }} port=8090
            connect_timeout=10 state=started
  when: overlord is defined and overlord
  # when: druid_role == "overlord" 

- name: Test that historical port is allocated
  wait_for: host={{ ansible_ec2_public_ipv4|default(ansible_default_ipv4.address) }} port=8083
            connect_timeout=10 state=started
  when: historical is defined and historical
  # when: druid_role == "historical" 

- name: Test that broker port is allocated
  wait_for: host={{ ansible_ec2_public_ipv4|default(ansible_default_ipv4.address) }} port=8082
            connect_timeout=10 state=started
  when: broker is defined and broker
  # when: druid_role == "broker" 

- name: Test that middleManager port is allocated
  wait_for: host={{ ansible_ec2_local_ipv4|default(ansible_default_ipv4.address) }} port=8091
            connect_timeout=10 state=started
  when: middleManager is defined and middleManager
  # when: druid_role == "middleManager" 

- name: Test that realtime port is allocated
  wait_for: host={{ ansible_ec2_public_ipv4|default(ansible_default_ipv4.address) }} port=8084
            connect_timeout=10 state=started
  when: router is defined and router
  # when: druid_role == "router"


