---
# This playbook contains common plays that will be run on all nodes.
- include_vars: "{{ item }}"
  with_first_found:
  - "../vars/{{ansible_distribution}}-{{ansible_distribution_version}}.yml"
  - "../vars/{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"
  - "../vars/{{ansible_distribution}}.yml"
  - "../vars/{{ansible_os_family}}.yml"
  - "../vars/default.yml"

- name: Update and upgrade the system
  when: ansible_os_family == "Debian"
  apt: update_cache=yes upgrade=dist
  tags:
    - apt

- name: Update and upgrade the system
  when: ansible_os_family == "RedHat"
  yum:
    name: '*'
    state: latest
  tags:
    - yum

# - name: Install epel-repository
#   when: ansible_os_family == "RedHat"
#   yum:
#     name: "{{ item }}"
#     state: installed
#   with_items:
#     - epel-release
#   tags:
#     - yum

- name: Install basic packages
  when: ansible_os_family == "Debian"
  apt: name={{ item }} state=present
  with_items:
    - "{{ DEFAULT_PACKAGES }}"
  tags:
    - apt

- name: Install basic packages
  when: ansible_os_family == "RedHat"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ DEFAULT_PACKAGES }}"
  tags:
    - yum
